### ISSUE TITLE
解决 AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

### ISSUE THREAD

**Issue by gangtie95** [liucongg/ChatGLM-Finetuning#119]
运行单卡 ChatGLM2的时候，报这个错
**报错 “AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'”**
问题解决，去ChatGLM2源码里面更新一下这个文件[tokenization_chatglm.py](https://huggingface.co/THUDM/chatglm2-6b/blob/main/tokenization_chatglm.py)的代码就好了

**Comment by liucongg** [comment]
因为官方代码更新啦，对应修改即可，项目中已经增加说明
