### ISSUE TITLE
peft==0.5.0怎么安装

### ISSUE THREAD

**Issue by zhl970124** [liucongg/ChatGLM-Finetuning#123]
运行代码的训练部分时报错：/xx/anaconda3/envs/llm/lib/python3.10/site-packages/peft/tuners/lora/model.py 
AttributeError: 'LoraModel' object has no attribute 'backward'
查看 peft版本发现是0.3.0
但是使用pip install peft==0.5.0 报错： 找不到0.5.0版本。请问如何解决这个问题
非常感谢！！

**Comment by liucongg** [comment]
pip install peft==0.5.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
