### ISSUE TITLE
 百度云盘的模型权重

### ISSUE THREAD

**Issue by sinan106** [liucongg/ChatGLM-Finetuning#14]
大佬，想问下为啥百度云里面的权重只有两个约2G的bin文件00001 和 00008，官方有个8个bin，想问下这有啥区别啊？

**Comment by JingerAI** [comment]
up
借楼问下：不能支持最新的chatGML模型么？百度云下载也太麻烦太慢了吧？

**Comment by liucongg** [comment]
下载官方1-8，8个模型，然后用我百度云里的1和8，替换官方原有的1和8模型

**Comment by OceannTwT** [comment]
建议提供一个git下载仓库 百度云也太慢了 @liucongg

**Comment by Test202010** [comment]
> 建议提供一个git下载仓库 百度云也太慢了 @liucongg

阿里云盘 也快一些 百度云太慢了

**Comment by JingerAI** [comment]
源码改的不多，把几个token的地方改一些就能支持官方最新的。

**Comment by starphantom666** [comment]
> 

大佬，方便可以写一下改了啥

**Comment by starphantom666** [comment]
> 源码改的不多，把几个pad token config配置改一下就能支持官方最新的。

大佬，方便可以写一下改了啥

**Comment by liucongg** [comment]
项目已更新，修改后无需网盘文件，官方模型即可训练
