### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu116

### ISSUE THREAD

**Issue by Test202010** [liucongg/ChatGLM-Finetuning#17]
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu116 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.13.1+cu116

使用清华源下载 报错如上

**Comment by liucongg** [comment]
torch需要用torch的官网源

**Comment by Test202010** [comment]
嗯嗯 
pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
我的实际操作 torchvision==0.14.1+cu116 也需要指定一下
