### ISSUE TITLE
RuntimeError: Internal: [MASK] is already defined.

### ISSUE THREAD

**Issue by bolongliu** [liucongg/ChatGLM-Finetuning#18]

**Comment by Test202010** [comment]
samehere.
$ CUDA_VISIBLE_DEVICES=0 deepspeed finetuning_freeze.py --num_train_epochs 5 --train_batch_size 2

RuntimeError: Internal: [MASK] is already defined.

**Comment by liucongg** [comment]
模型版本的问题，请用百度云模型进行替换
