### ISSUE TITLE
finetuning_freeze.py训练中断之后 重新运行命令  不支持继续微调

### ISSUE THREAD

**Issue by Test202010** [liucongg/ChatGLM-Finetuning#22]
之前已经训练到 2880步了
![image](https://user-images.githubusercontent.com/73330797/231673949-f47ea40e-ad17-42da-aff8-62297e0f8ed6.png)
程序因为磁盘满，中断
清理磁盘，再重新运行命令，程序从0步开始。。。
![image](https://user-images.githubusercontent.com/73330797/231674350-94dad284-a44c-4c01-bbf8-a1eebbfc0b29.png)

**Comment by liucongg** [comment]
没有设置断点续训练

**Comment by liangxiaonasummer** [comment]
> 没有设置断点续训练

全量微调也没有设置断点续训练么？
