### ISSUE TITLE
数据泄露

### ISSUE THREAD

**Issue by LebronJames0423** [liucongg/ChatGLM-Finetuning#24]
请问下，为什么会出现大模型数据泄露啊，原理是什么，什么情况会导致数据泄露呢？谢谢
![image](https://user-images.githubusercontent.com/33833521/231920196-1a5b71b3-b235-4ba3-a759-a7ccdd08ddf8.png)

**Comment by netwolf712** [comment]
我的理解就是模型保存了学习过的数据，它的回答都是从学习过的知识库里获取的。如果之前学习的内容涉密，那它就会口无遮拦地把涉密内容都吐出来了。

**Comment by LebronJames0423** [comment]
> 我的理解就是模型保存了学习过的数据，它的回答都是从学习过的知识库里获取的。如果之前学习的内容涉密，那它就会口无遮拦地把涉密内容都吐出来了。

好的明白了，谢谢
