### ISSUE TITLE
模型训练时的数据长度

### ISSUE THREAD

**Issue by netwolf712** [liucongg/ChatGLM-Finetuning#25]
您好，看到您这里介绍模型训练时的最大输入长度是768，官方的方法好像默认的只有几十，请问这是做了什么优化吗？
我们也整需要做信息抽取的工作，输入的数据比较大，看到你这个数据很是惊喜。
本人小白，还请指教。

**Comment by liucongg** [comment]
长度越大吃的显存越多，很多微调为了节省显存，所以把最大长度设置的较小。原本chatglm-60的最大长度应该是2048。
