### ISSUE TITLE
PT和PT-Only-Embedding

### ISSUE THREAD

**Issue by ZTurboX** [liucongg/ChatGLM-Finetuning#33]
PT和PT-Only-Embedding这两种训练方法是如何设置的。官方的ptuning v2微调后文本生成效果好差

**Comment by liucongg** [comment]
修改代码中prefix_projection参数，True为PT，False为PT-Only-Embedding，PT-Only-Embedding相当于PT-v1，PT相当于PT-v2

**Comment by neilzhu89** [comment]
> 修改代码中prefix_projection参数，True为PT，False为PT-Only-Embedding，PT-Only-Embedding相当于PT-v1，PT相当于PT-v2

请问一下，在ChatGLM官方代码里的ptuning里，prefix_projection为False为PT-v2，那里的prefix_projection和这里的prefix_projection是一个东西吗？

**Comment by liucongg** [comment]
代码已经更新，readme中有不同参数显存占比
