### ISSUE TITLE
请问有尝试过全量微调的方式吗？大概需要多少张V100才能训得动

### ISSUE THREAD

**Issue by wenHK** [liucongg/ChatGLM-Finetuning#45]

**Comment by liucongg** [comment]
全量微调zero3开offload两张A40即可，代码已更新，增加全量调参请参考

**Comment by Yuxiang1990** [comment]
full的情况
![image](https://github.com/user-attachments/assets/aa2764d6-3d52-459f-95cc-4fe937c98e45)
