### ISSUE TITLE
mpi4py

### ISSUE THREAD

**Issue by huangtao36** [liucongg/ChatGLM-Finetuning#5]
在deepspeed.initialize函数中，有需要mpi4py这个包，但是pip install装不上，
<img width="732" alt="image" src="https://user-images.githubusercontent.com/27218434/230711490-167e9969-0233-486c-83c2-40a3d5ff52b5.png">

sudo apt-get install libopenmpi-dev  后再装也不行，还是一样的报错

**Comment by liucongg** [comment]
不清楚唉，我是直接装上的，我的环境python3.8，你的环境呢，是否pip需要upgrade

**Comment by NBtree** [comment]
我是conda装上的

**Comment by yangliuIOC** [comment]
我也装不上

**Comment by superbigsea** [comment]
手动用conda装

**Comment by dongcin** [comment]
sudo apt update
sudo apt-get install libopenmpi-dev -y 
pip install mpi4py
我这样就可以了
