### ISSUE TITLE
单机多卡训练，好像并没有多卡起来？

### ISSUE THREAD

**Issue by KOD-Chen** [liucongg/ChatGLM-Finetuning#54]
比如，设置2张卡：CUDA_VISIBLE_DEVICES=0,1
batchsize=10，一共1000条数据。
训练代码中指定训练一个epoch后，会保存一个checkpoint。

按照设置，2张卡、batch=10，训练一个epoch应该是50 step保存checkpoint。
但是实际上是100 step保存了checkpoint。

看了gpu利用率，两张卡确实都在使用。
求解。感觉多卡设置没有什么用？

**Comment by nicole828** [comment]
这个解决了么

**Comment by liucongg** [comment]
项目已更新，支持多卡训练
