### ISSUE TITLE
[模型加载] 微调后的模型加载

### ISSUE THREAD

**Issue by sxinyuhoo** [liucongg/ChatGLM-Finetuning#55]
使用了freeze方法微调后，应该如何加载使用？

**Comment by qianranow** [comment]
你好，百度网盘的模型文件是不是少了呀

**Comment by sxinyuhoo** [comment]
> 使用了freeze方法微调后，应该如何加载使用？

当加载微调好的模型后，执行
`model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)`时，会报错，missing_keys。
如果修改为`model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict, strict=False)`后可以加载，但看不出训练的效果。
是否加载模型时采用的方法不对？是否有相关示例说明可以参考？

**Comment by pythonla** [comment]
> 你好，百度网盘的模型文件是不是少了呀

我也遇到这个问题了，bin文件应该是8个

**Comment by liucongg** [comment]
项目已更新，修改后无需网盘文件，官方模型即可训练

**Comment by pythonla** [comment]
这是来自QQ邮箱的假期自动回复邮件。你发给我的信件已经收到。谢谢!
