### ISSUE TITLE
网盘权重文件是不是少了？

### ISSUE THREAD

**Issue by qianranow** [liucongg/ChatGLM-Finetuning#56]
No such file or directory: '/home/xxx/ChatGLM-6B/pytorch_model-00002-of-00008.bin'

**Comment by sxinyuhoo** [comment]
02-07.bin文件直接用chatglm-6b提供的即可

**Comment by qianranow** [comment]
torch==1.13.1+cu116 这个是通过conda安装吗？

**Comment by sxinyuhoo** [comment]
> torch==1.13.1+cu116 这个是通过conda安装吗？

pip cond都可以

**Comment by qianranow** [comment]
谢谢哈~
