### ISSUE TITLE
基础模型权重加载问题，有人遇到过吗？

### ISSUE THREAD

**Issue by niexufei** [liucongg/ChatGLM-Finetuning#59]
加载模型时有如下warning，感觉不正常，大家有人遇到过吗？多谢
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /home/chatGPT/model/chatGLMModel/liucongg/ChatGLM-6B/ and are newly initialized: ['transformer.prefix_encoder.embedding.weight', 'transformer.prefix_encoder.trans.0.weight', 'transformer.prefix_encoder.trans.2.weight', 'transformer.prefix_encoder.trans.2.bias', 'transformer.prefix_encoder.trans.0.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
trainable params: 956600320 || all params: 4394266624 || trainable%: 21.76928260964804
transformer.prefix_encoder.embedding.weight
transformer.prefix_encoder.trans.0.weight
transformer.prefix_encoder.trans.0.bias
transformer.prefix_encoder.trans.2.weight
transformer.prefix_encoder.trans.2.bias
[2023-05-16 17:02:31,667] [INFO] [logging.py:75:log_dist] [Rank -1] DeepSpeed info: version=0.8.1, git-hash=unknown, git-branch=unknown
[2023-05-16 17:02:31,669] [INFO] [comm.py:657:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2023-05-16 17:02:31,729] [INFO] [logging.py:75:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False

**Comment by niexufei** [comment]
我好想知道怎么回事了，prefix_encoder.x这样的参数在基础模型中本来是没有的，需要精调训练的，所以这几层参数加载不上是正常的。

**Comment by niexufei** [comment]
我好想知道怎么回事了，prefix_encoder.x这样的参数在基础模型中本来是没有的，需要精调训练的，所以这几层参数加载不上是正常的。

**Comment by Justsosostar** [comment]
我也是遇到这样的问题
