### ISSUE TITLE
[MASK] is already defined.

### ISSUE THREAD

**Issue by xioozq** [liucongg/ChatGLM-Finetuning#6]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/ChatGLM-Finetuning/finetuning_lora.py:151 in <module>                                      │
│                                                                                                  │
│   148                                                                                            │
│   149                                                                                            │
│   150 if __name__ == "__main__":                                                                 │
│ ❱ 151 │   main()                                                                                 │
│   152 │   # CUDA_VISIBLE_DEVICES=2 deepspeed --master_port 5555 finetuning_lora.py               │
│   153                                                                                            │
│                                                                                                  │
│ /root/ChatGLM-Finetuning/finetuning_lora.py:63 in main                                           │
│                                                                                                  │
│    60 │   args = set_args()                                                                      │
│    61 │                                                                                          │
│    62 │   model = ChatGLMForConditionalGeneration.from_pretrained(args.model_dir)                │
│ ❱  63 │   tokenizer = ChatGLMTokenizer.from_pretrained(args.model_dir)                           │
│    64 │                                                                                          │
│    65 │   config = LoraConfig(r=args.lora_r,                                                     │
│    66 │   │   │   │   │   │   lora_alpha=32,                                                     │
│                                                                                                  │
│ /root/miniconda3/envs/glm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1 │
│ 804 in from_pretrained                                                                           │
│                                                                                                  │
│   1801 │   │   │   else:                                                                         │
│   1802 │   │   │   │   logger.info(f"loading file {file_path} from cache at {resolved_vocab_fil  │
│   1803 │   │                                                                                     │
│ ❱ 1804 │   │   return cls._from_pretrained(                                                      │
│   1805 │   │   │   resolved_vocab_files,                                                         │
│   1806 │   │   │   pretrained_model_name_or_path,                                                │
│   1807 │   │   │   init_configuration,                                                           │
│                                                                                                  │
│ /root/miniconda3/envs/glm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1 │
│ 959 in _from_pretrained                                                                          │
│                                                                                                  │
│   1956 │   │                                                                                     │
│   1957 │   │   # Instantiate tokenizer.                                                          │
│   1958 │   │   try:                                                                              │
│ ❱ 1959 │   │   │   tokenizer = cls(*init_inputs, **init_kwargs)                                  │
│   1960 │   │   except OSError:                                                                   │
│   1961 │   │   │   raise OSError(                                                                │
│   1962 │   │   │   │   "Unable to load vocabulary from file. "                                   │
│                                                                                                  │
│ /root/ChatGLM-Finetuning/tokenization_chatglm.py:212 in __init__                                 │
│                                                                                                  │
│   209 │   │   self.mask_token = mask_token                                                       │
│   210 │   │   self.gmask_token = gmask_token                                                     │
│   211 │   │                                                                                      │
│ ❱ 212 │   │   self.sp_tokenizer = SPTokenizer(vocab_file)                                        │
│   213 │   │                                                                                      │
│   214 │   │   """ Initialisation """                                                             │
│   215                                                                                            │
│                                                                                                  │
│ /root/ChatGLM-Finetuning/tokenization_chatglm.py:32 in __init__                                  │
│                                                                                                  │
│    29 │   │   self.special_tokens = ["[MASK]", "[gMASK]", "[sMASK]", "<unused_0>", "<sop>", "<   │
│    30 │   │   self.max_blank_length = max_blank_length                                           │
│    31 │   │   self.byte_fallback = byte_fallback                                                 │
│ ❱  32 │   │   self.text_tokenizer = self._build_text_tokenizer(encode_special_tokens=False)      │
│    33 │   │   self.special_text_tokenizer = self._build_text_tokenizer(encode_special_tokens=T   │
│    34 │                                                                                          │
│    35 │   @staticmethod                                                                          │
│                                                                                                  │
│ /root/ChatGLM-Finetuning/tokenization_chatglm.py:65 in _build_text_tokenizer                     │
│                                                                                                  │
│    62 │                                                                                          │
│    63 │   def _build_text_tokenizer(self, encode_special_tokens=False):                          │
│    64 │   │   tokenizer = TextTokenizer(self.vocab_file)                                         │
│ ❱  65 │   │   self._configure_tokenizer(                                                         │
│    66 │   │   │   tokenizer, self.special_tokens, self.max_blank_length, self.byte_fallback, e   │
│    67 │   │   )                                                                                  │
│    68 │   │   return tokenizer                                                                   │
│                                                                                                  │
│ /root/ChatGLM-Finetuning/tokenization_chatglm.py:61 in _configure_tokenizer                      │
│                                                                                                  │
│    58 │   │   │   │   text_tokenizer.proto.pieces.append(                                        │
│    59 │   │   │   │   │   sp_model.ModelProto.SentencePiece(piece="<0x{:02X}>".format(i), scor   │
│    60 │   │   │   │   )                                                                          │
│ ❱  61 │   │   text_tokenizer.refresh()                                                           │
│    62 │                                                                                          │
│    63 │   def _build_text_tokenizer(self, encode_special_tokens=False):                          │
│    64 │   │   tokenizer = TextTokenizer(self.vocab_file)                                         │
│                                                                                                  │
│ /root/miniconda3/envs/glm/lib/python3.10/site-packages/icetk/text_tokenizer.py:31 in refresh     │
│                                                                                                  │
│   28 │                                                                                           │
│   29 │   def refresh(self):                                                                      │
│   30 │   │   self.sp = spm.SentencePieceProcessor()                                              │
│ ❱ 31 │   │   self.sp.Load(model_proto=self.proto.SerializeToString())                            │
│   32 │   │   self.num_tokens = self.sp.vocab_size()                                              │
│   33 │                                                                                           │
│   34 │   def add_special_tokens(self, tokens):                                                   │
│                                                                                                  │
│ /root/miniconda3/envs/glm/lib/python3.10/site-packages/sentencepiece/__init__.py:904 in Load     │
│                                                                                                  │
│    901 │     if model_file and model_proto:                                                      │
│    902 │   │   raise RuntimeError('model_file and model_proto must be exclusive.')               │
│    903 │     if model_proto:                                                                     │
│ ❱  904 │   │   return self.LoadFromSerializedProto(model_proto)                                  │
│    905 │     return self.LoadFromFile(model_file)                                                │
│    906                                                                                           │
│    907                                                                                           │
│                                                                                                  │
│ /root/miniconda3/envs/glm/lib/python3.10/site-packages/sentencepiece/__init__.py:250 in          │
│ LoadFromSerializedProto                                                                          │
│                                                                                                  │
│    247 │   __swig_destroy__ = _sentencepiece.delete_SentencePieceProcessor                       │
│    248 │                                                                                         │
│    249 │   def LoadFromSerializedProto(self, serialized):                                        │
│ ❱  250 │   │   return _sentencepiece.SentencePieceProcessor_LoadFromSerializedProto(self, seria  │
│    251 │                                                                                         │
│    252 │   def SetEncodeExtraOptions(self, extra_option):                                        │
│    253 │   │   return _sentencepiece.SentencePieceProcessor_SetEncodeExtraOptions(self, extra_o  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Internal: [MASK] is already defined.

**Comment by liucongg** [comment]
官方模型一直再更新，是否跟这个有关，我这边没有遇到这个问题。

**Comment by xioozq** [comment]
> 官方模型一直再更新，是否跟这个有关，我这边没有遇到这个问题。

如果是因为官方模型更新了，那这边需要怎么调整呢？

**Comment by km1994** [comment]
> 官方模型一直再更新，是否跟这个有关，我这边没有遇到这个问题。

能不能发一下你本地版本，我也遇到这个问题

**Comment by liucongg** [comment]
我的版本模型，可以更新本地模型，尝试一下，是否还存在问题
链接：https://pan.baidu.com/s/1-UrZWnqw6Ciyo5K2NLraDg 
提取码：jh0l

**Comment by aihebaikaishui** [comment]
如果模型用的最新的话，tokenization_chatglm.py 换成配套的就可以了

**Comment by phellonchen** [comment]
百度云盘了为什么没有2-7呢？

**Comment by liucongg** [comment]
> 

2-7跟官方最新版模型一致

**Comment by z1968357787** [comment]
> 如果模型用的最新的话，tokenization_chatglm.py 换成配套的就可以了

你好，请问一下他仓库的配套tokenization_chatglm.py在哪里呢，我好像找不到

**Comment by aihebaikaishui** [comment]
> > 如果模型用的最新的话，tokenization_chatglm.py 换成配套的就可以了
> 
> 你好，请问一下他仓库的配套tokenization_chatglm.py在哪里呢，我好像找不到

https://huggingface.co/THUDM/chatglm-6b/tree/main  模型和tokenization_chatglm.py 都用这里的就配套了

**Comment by z1968357787** [comment]
好的非常感谢！！&nbsp;


变质的水果糖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hao ***@***.***&gt;; 
发送时间: 2023年4月11日(星期二) 下午4:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liucongg/ChatGLM-Finetuning] [MASK] is already defined. (Issue #6)





   
如果模型用的最新的话，tokenization_chatglm.py 换成配套的就可以了
  
你好，请问一下他仓库的配套tokenization_chatglm.py在哪里呢，我好像找不到
  
https://huggingface.co/THUDM/chatglm-6b/tree/main  模型和tokenization_chatglm.py 都用这里的就配套了

**Comment by OceannTwT** [comment]
给一个提议 模型文件可以建一个仓库吗 发到网盘来下载实在是太麻烦了

**Comment by Test202010** [comment]
> > > 如果模型用的最新的话，tokenization_chatglm.py 换成配套的就可以了
> > 
> > 
> > 你好，请问一下他仓库的配套tokenization_chatglm.py在哪里呢，我好像找不到
> 
> https://huggingface.co/THUDM/chatglm-6b/tree/main 模型和tokenization_chatglm.py 都用这里的就配套了

使用配套的tokenization_chatglm.py 之后 [MASK] is already defined.的问题解决了
但是 执行CUDA_VISIBLE_DEVICES=0 deepspeed finetuning_freeze.py --num_train_epochs 5 --train_batch_size 2 又遇到了新问题
ValueError: 150001 is not in list

**Comment by ghqing0310** [comment]
> > > > 如果模型用的最新的话，tokenization_chatglm.py 换成配套的就可以了
> > > 
> > > 
> > > 你好，请问一下他仓库的配套tokenization_chatglm.py在哪里呢，我好像找不到
> > 
> > 
> > https://huggingface.co/THUDM/chatglm-6b/tree/main 模型和tokenization_chatglm.py 都用这里的就配套了
> 
> 使用配套的tokenization_chatglm.py 之后 [MASK] is already defined.的问题解决了 但是 执行CUDA_VISIBLE_DEVICES=0 deepspeed finetuning_freeze.py --num_train_epochs 5 --train_batch_size 2 又遇到了新问题 ValueError: 150001 is not in list

我也是，请问解决了吗？

**Comment by dylgithub** [comment]
官方代码更新了，可以打印tokenizer看一下，现在只有13000多个token了。注意代码中聪大佬加载模型和tokenizer的方法，是从该项目下的相关文件中加载的，可以去[Hugging Face](https://huggingface.co/)更新最新的相关文件，然后使用transformers提供的AutoTokenizer, AutoModel加载模型和tokenizer，就不会报类似150001相关的错了

**Comment by liucongg** [comment]
代码已经更新到0.2，GLM1的代码和模型使用最新的即可
