### ISSUE TITLE
predict_lora.py运行显示应有四个维度但是现在接受的只有三个维度

### ISSUE THREAD

**Issue by ZhongmeiWong** [liucongg/ChatGLM-Finetuning#60]
lora微调之后运行predict_lora.py显示input有问题
![image](https://github.com/liucongg/ChatGLM-Finetuning/assets/129704989/79505606-3278-4b06-958f-f2d0db15cc7b)

**Comment by Essence9999** [comment]
在你微调生成的模型文件中，找到adapter_config.json文件，修改其中的inference_mode参数，改成false，再运行predict_lora.py

**Comment by liucongg** [comment]
> 在你微调生成的模型文件中，找到adapter_config.json文件，修改其中的inference_mode参数，改成false，再运行predict_lora.py

是的

**Comment by liucongg** [comment]
项目已经更新，不会出现类似问题
