### ISSUE TITLE
用chatGLM ptuning微调之后的一些问题。

### ISSUE THREAD

**Issue by SMR-S** [liucongg/ChatGLM-Finetuning#63]
单轮的QA回答的还不错，但是多轮对话时，就会出现瞎回答的情况。我感觉应该是多轮对话的history记录干扰了回答的效果？目前还不确定是不是这样的情况，有兄弟遇到类似的情况吗？交流一波啊！

**Comment by liucongg** [comment]
你用是吗数据进行微调的
