### ISSUE TITLE
关于源码的疑问？

### ISSUE THREAD

**Issue by apachemycat** [liucongg/ChatGLM-Finetuning#64]
tokens = prompt_tokens + src_tokens + ["[gMASK]", "<sop>"]
这里的["[gMASK]" 与"<sop>"这个数组的作用是什么？ChatGLM中也没有提过的

**Comment by liucongg** [comment]
[gMASK]在预训练阶段是掩盖长字符串，[MASK]掩盖短字符串

**Comment by apachemycat** [comment]
多谢答复
