### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by fxb392** [liucongg/ChatGLM-Finetuning#66]
设置os.environ["CUDA_VISIBLE_DEVICES"] = "2, 3, 4" 了多卡训练一直报OutOfMemoryError: CUDA out of memory.怎么回事

**Comment by xiaolingcom** [comment]
> 设置os.environ["CUDA_VISIBLE_DEVICES"] = "2, 3, 4" 了多卡训练一直报OutOfMemoryError: CUDA out of memory.怎么回事

我也是，然后用单卡CUDA_VISIBLE_DEVICES=0跑起来了..

**Comment by liucongg** [comment]
代码已更新
