### ISSUE TITLE
你好 CUDA_VISIBLE_DEVICES=0 deepspeed finetuning_freeze.py --num_train_epochs 5 --train_batch_size 2 报错 ，exits with return code = -7

### ISSUE THREAD

**Issue by wuxiaobo** [liucongg/ChatGLM-Finetuning#67]
<img width="1222" alt="image" src="https://github.com/liucongg/ChatGLM-Finetuning/assets/5646265/64107478-c120-4305-baed-bee51d1aeb4a">
想请教为什么，一张显卡

**Comment by liucongg** [comment]
应该你已经起了一个服务，端口呗占用了，尝试修改deepspeed端口CUDA_VISIBLE_DEVICES=0 deepspeed --master_port 5524 train.py

**Comment by xxtyy** [comment]
我也是报错但是我用的两张显卡CUDA_VISIBLE_DEVICES=0,1 deepspeed finetuning_pt.py --model_dir /opt/ChatGLM-Finetuning/ChatGLM-6B/ 报错[2023-07-18 09:02:14,830] [ERROR] [launch.py:321:sigkill_handler] ['/opt/ChatGLM-Finetuning/venv/bin/python', '-u', 'finetuning_pt.py', '--local_rank=1', '--model_dir', '/opt/ChatGLM-Finetuning/ChatGLM-6B/', '--output_dir', '/opt/'] exits with return code = -9

**Comment by liucongg** [comment]
代码已更新，请用最新版代码

**Comment by yhx0105** [comment]
> 

大佬，这个问题你解决了吗

**Comment by yhx0105** [comment]
> 我也是报错但是我用的两张显卡CUDA_VISIBLE_DEVICES=0,1 deepspeed finetuning_pt.py --model_dir /opt/ChatGLM-Finetuning/ChatGLM-6B/ 报错[2023-07-18 09:02:14,830] [ERROR] [launch.py:321:sigkill_handler] ['/opt/ChatGLM-Finetuning/venv/bin/python', '-u', 'finetuning_pt.py', '--local_rank=1', '--model_dir', '/opt/ChatGLM-Finetuning/ChatGLM-6B/', '--output_dir', '/opt/'] exits with return code = -9

大佬，这个问题你解决了吗
