### ISSUE TITLE
使用V100 32GB报GPU显存不足，大家的显卡都多大呀

### ISSUE THREAD

**Issue by xiaofensi11223** [liucongg/ChatGLM-Finetuning#73]
使用V100 32GB报GPU显存不足，大家的显卡都多大呀
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 31.74 GiB total capacity; 30.41 GiB already allocated; 98.12 MiB free; 30.53 GiB reserved in total by PyTorch)

**Comment by liucongg** [comment]
我补充了模型的显存占用情况，显存不够可以修改配置参数
