### ISSUE TITLE
网盘里面的00008模型加载时报错？

### ISSUE THREAD

**Issue by qian2020** [liucongg/ChatGLM-Finetuning#78]
OSError: Unable to load weights from pytorch checkpoint file for '/root/autodl-tmp/ChatGLM-Finetuning/public_model_path/ChatGLM-6B/pytorch_model-00008-of-00008.bin' at '/root/autodl-tmp/ChatGLM-Finetuning/public_model_path/ChatGLM-6B/pytorch_model-00008-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
如下是截图：
![chatglm](https://github.com/liucongg/ChatGLM-Finetuning/assets/32272555/2a024b3b-fcb7-41c2-a3f6-292e0ec6bce5)

**Comment by liucongg** [comment]
代码已更新，直接使用最新模型就行，无需模型修改了
