### ISSUE TITLE
src文件无法查看

### ISSUE THREAD

**Issue by Alan-JW** [liucongg/ChatGLM-Finetuning#80]
@liucongg ，您好，请问src文件夹中的文件好像现在无法查看了
![image](https://github.com/liucongg/ChatGLM-Finetuning/assets/74579183/b387af65-7c06-49f0-b0b5-e10d11fdf6a4)

**Comment by liucongg** [comment]
![image](https://github.com/liucongg/ChatGLM-Finetuning/assets/45169043/a110c7fe-78fa-4922-b214-9eb42c8a1aea)
我没有src文件夹呀

**Comment by Alan-JW** [comment]
from peft import LoraConfig, get_peft_model，我从get_peft_model函数跳转过去的

**Comment by liucongg** [comment]
那你是本地安装的peft，通过pycharm可以看
