### ISSUE TITLE
训练参数设置

### ISSUE THREAD

**Issue by ShawnChang-ei** [liucongg/ChatGLM-Finetuning#82]
首先感谢开源，浅读了一下代码，有以下疑问：
1、单卡下还有必要设置deepspeed吗？
2、max_len、max_source_len、pre_seq_len三者之间，是包含的关系吗？
3、关于freeze_module_name的设置有什么先验经验吗？

**Comment by liucongg** [comment]
单卡需要设置deepspeed，因为训练用了zero。
max_len和max_source_len值包含关系，pre_seq_len是p-tuning训练所需参数。
freeze_module_name一般设置后面几层

**Comment by ShawnChang-ei** [comment]
但是单卡训练设置zero没有什么优势吧，不存在切片和通信的问题
另外有几个新的问题，望解答：
1、全参微调的最低配置要求是什么样？
2、p-tuning微调后保存的是完整模型吧，后续用于推理的时候，直接使用from_pretrained加载就可以吧
3、想讨论下多轮数据的构造方式，如果采用one_step的方式，我预想的是
[gMASK][sop]input1<eos>target1<eos>input2<eos>target2<eos>... 
input部分的loss不参与参数更新，只有target部分的loss参与参数更新，但试了一下loss跑飞了，是否因为添加的special_tokens有问题
