### ISSUE TITLE
预测代码都没得？ 

### ISSUE THREAD

**Issue by Adam86546853** [liucongg/ChatGLM-Finetuning#93]
lora 调完了， 和base模型合并参数，  官方加载模型方式也没法用。

**Comment by liucongg** [comment]
lora 调完了， 和base模型合并参数，就跟原始参数一致呀，怎么可以没法用？

**Comment by Benjamin2333** [comment]
lora合并参数使用的代码在哪里，有老哥发一份help一下吗

**Comment by liucongg** [comment]
拉取最新代码
