### ISSUE TITLE
The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:520 (errno: 13 - Permission denied). 

### ISSUE THREAD

**Issue by yc930401** [liucongg/ChatGLM-Finetuning#97]
跑不起来
![image](https://github.com/liucongg/ChatGLM-Finetuning/assets/25715774/c20111dc-70cf-46ff-a2cf-41d01eae6dc4)

**Comment by yc930401** [comment]
嗷嗷，好像是520端口被占用了，换成其他的ok了

**Comment by origi6615** [comment]
> 嗷嗷，好像是520端口被占用了，换成其他的ok了

你好，请问具体是如何解决的，要修改什么命令吗，谢谢！

**Comment by EricShenYuQi** [comment]
同问，求助！
